### ISSUE TITLE
Unable to Register Trainer

### ISSUE THREAD

**Issue by sarahsotomayor** [WilliamTRich/CodeZeroProject#19]
Per Kate from Discord chat (recording here for tracking):

DB: it is connected but registering a trainer isn't working and I am not sure why

![image](https://github.com/WilliamTRich/CodeZeroProject/assets/116047642/6177d88d-1245-4fff-9683-d789a6f5ee84)

![image](https://github.com/WilliamTRich/CodeZeroProject/assets/116047642/cd332584-a040-4771-841b-8e0b0c814f53)

![image](https://github.com/WilliamTRich/CodeZeroProject/assets/116047642/f8e03ff2-4c2b-4618-8f33-aecdc6e4386d)

**Comment by sarahsotomayor** [comment]
To add - unable to register user and test that as well because a user needs to be connected to a trainer.

**Comment by Pauljsyi** [comment]
make sure that you select json instead of text in the dropdown on the right.

![image](https://github.com/WilliamTRich/CodeZeroProject/assets/43303711/57f61386-e05a-4774-ba0b-e024c7704a1f)
